CREATE TABLE el_sentence_audio (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 sentence_id BIGINT UNSIGNED NOT NULL,
 text_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 file_name VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 file_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 voice VARCHAR(100) NOT NULL,
 rate SMALLINT UNSIGNED NOT NULL,
 duration_ms INT UNSIGNED NOT NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 is_del TINYINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (id),
 UNIQUE KEY uk_audio_sentence (sentence_id),
 CONSTRAINT fk_audio_sentence FOREIGN KEY (sentence_id) REFERENCES el_sentences(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
