CREATE TABLE el_episode_video (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 episode_id BIGINT UNSIGNED NOT NULL,
 file_name VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 file_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 duration_ms INT UNSIGNED NOT NULL,
 width SMALLINT UNSIGNED NOT NULL,
 height SMALLINT UNSIGNED NOT NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 is_del TINYINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (id),
 UNIQUE KEY uk_video_episode (episode_id),
 CONSTRAINT fk_video_episode FOREIGN KEY (episode_id) REFERENCES el_episodes(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE el_sentence_video (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 sentence_id BIGINT UNSIGNED NOT NULL,
 video_id BIGINT UNSIGNED NOT NULL,
 video_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 text_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 start_ms INT UNSIGNED NOT NULL,
 end_ms INT UNSIGNED NOT NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 is_del TINYINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (id),
 UNIQUE KEY uk_video_sentence (sentence_id),
 KEY idx_sentence_video (video_id),
 CONSTRAINT fk_video_sentence FOREIGN KEY (sentence_id) REFERENCES el_sentences(id),
 CONSTRAINT fk_sentence_video FOREIGN KEY (video_id) REFERENCES el_episode_video(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
